version: '3.7'
services: 
  service1:
    build: ./service1/.
    image: iwantm/rng:service1
    deploy:
      replicas: 3
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    depends_on:
    - "service2"
    - "service3"
    - "service4"
    - "database"
  service2:
    build: ./service2/.
    image: iwantm/rng:service2
    deploy:
      replicas: 4
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  service3:
    build: ./service3/.
    image: iwantm/rng:service3
    deploy:
      replicas: 3
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
  service4:
    build: ./service4/.
    image: iwantm/rng:service4
    environment: 
      API_CODE: ${API_CODE}
    deploy:
      replicas: 4
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
    depends_on:
    - "service2"
    - "service3"

  database:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: name-db
    deploy:
      replicas: 4
    ports:
    - target: 3306
      published: 3306
    volumes:
      - type: bind
        source: ./CreateTables.sql
        target: /docker-entrypoint-initdb.d/CreateTables.sql