- name: Install required system packages
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present 

- name: Update apt packages
  apt:
    update_cache: "yes"
    force_apt_get: "yes"

- name: Install Docker
  apt: 
    name: "docker-ce"
    state: present

- name: Create docker group
  group:
    name: "docker"
    state: present
  
- name: Adding user {{ ansible_user }} to docker group  
  user:
    name: "{{ ansible_user }}"
    groups: "docker"
    append: "yes"

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
    dest: "/usr/local/bin/docker-compose"
    mode: 0755

- name: "Install Python Docker module"
  pip:
    name:
    - docker
    - jsondiff