- hosts: all
  become: true
  roles:
  - common
- hosts: manager
  become: true
  roles:
  - manager
- hosts: worker
  become: true
  roles:
  - worker
- hosts: nginx
  become: true
  roles:
  - nginx